{% set name = "easywatch" %}
{% set version = "0.0.4" %}
{% set sha256 = "e7128dd787db73839051c1ec55e0b497b0a6256b8a4a56d7e91a14741a35a041" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - watchdog

test:
  imports:
    - easywatch

about:
  home: https://github.com/Ceasar/easywatch
  license: MIT
  license_family: MIT
  license_file: LICENSE  # in recipe: https://github.com/Ceasar/easywatch/pull/11#issuecomment-413243017
  summary: 'Dead-simple way to watch a directory'
  dev_url: https://github.com/Ceasar/easywatch

extra:
  recipe-maintainers:
    - dougalsutherland
