{% set name = "easywatch" %}
{% set version = "0.0.5" %}
{% set sha256 = "0cded70106083eade6e32f66eef1f9400cb039f4c6f70e91c4499ffda26480ac" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - watchdog

test:
  imports:
    - easywatch

about:
  home: https://github.com/Ceasar/easywatch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Dead-simple way to watch a directory'
  dev_url: https://github.com/Ceasar/easywatch

extra:
  recipe-maintainers:
    - djsutherland
