{% set name = "easywatch" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0cded70106083eade6e32f66eef1f9400cb039f4c6f70e91c4499ffda26480ac

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - watchdog

test:
  requires:
    - python {{ python_min }}
  imports:
    - easywatch

about:
  home: https://github.com/Ceasar/easywatch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Dead-simple way to watch a directory'
  dev_url: https://github.com/Ceasar/easywatch

extra:
  recipe-maintainers:
    - djsutherland
