travis:
  secure:
    BINSTAR_TOKEN: TZ8P2KZKCJWsDk4K9HOENXgVddVKGNBZijY+nRAND4o7PmdEfBbcCxiF2x/huR6iInmEuewxTJKuky2G0b2mL2MsuRNgGf7h+5SLnNOX6h+uUqsFmLznp0lG7wwPw1yR1QeGlK4F30uU5FrVtkC6KJa30rRK7pn+xiQPKzmGzWz43k5jFLuVYyweU33+psHVIUmWFglXuCGvH/6fBo6YmT37fAFx8xoAOI2a9PKj4SlG9i0qGUHrfP1sb0BFjWJQcWIEqCEBzro3/KWDGYJkmBcBuE2veFOaSnVPsh1je9LGE71kE2AIkKZ3GqEeCpMNyLu0Erq98DfgnnlIosOPFPfWCW0FFTyls1oNh9+J8fYumqQSj/hQY0rF4cK9T/UmuKAF92RGduIIrD6esDDZUGRhqg7PtWLbbsnbOHfFk75PzI9m/f6b0UiXsewB4eh83ghiu2Jr2nD1xc9FbW5w7kaweU7EieMsNTVqaNlBhIvA/+h1vLYZ9LEbFUGGCxVENYQ4SmxVZWPedbWk+yBMR8iZU8r+4hZCqL9EPp/JBGNwjjBll4pKzBYv1Tx+/I32PQmdYnRzZS3FpWA3R8DNu0UF1b0D+FuD7YMM0vbHsEi6tK7RwTLBv4wbzebDkmO9B/yedAOBkZMFCfN884AspCyaUTcqJ/LdlfqvzHPKK7U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
