travis:
  secure:
    BINSTAR_TOKEN: kj9fzboM7KGmVIop3lDnf8tPSVeRErAzTupvjfT2a9WSGVD7e+a6GCECMpTJ1MxTFRNU/QEoC9/YhuaAtwryaBgfX2DTk0NB+0mSIyr9NycOTrkDBTbJfAvVS9zpnHng3nPR71YmJsXFzrsGgTWmKaLGNKWxJaHgcetgA/ra9x5Kj+LxNVoWqJy/mTjITOhtS6NCvhVkI2JEXgRG0wfq4pwm9AoF9mySDlrR+TvPmyc9x0gLreJgt7Ojy6N3UWFPc8/IOWn7jwpcgw49XHkHrqOLwa7OUK4mdHqR4+eB+9aONoaZVXKGAGSkbN5q46LNKk0d3COg2kII5ymyjKjZT7Y0BXa/JY9GzcoIsJyXKbr86uic3nnZRKgfwCyUJ+AjfN+Xhuq0bio+yFJXoypWmGRxfOAhsjKeMVA3JYdWs3IozrT3A0ItcTL1oyXxmp2rrRJTXoUedntqfya07nKYfIprmJpnY4c4WniPx72+r+43yWHgbKWOHEfuyxNPEmR0YGzgntepteiDipkHRIMs8QE3bfj1nR6V1sWUuY/34btUfCu/oczhCss3XU0qFksCQCgMrKzIMBmA/fuUVFW4+3P0hSviBjMJpsjH2D+pVOT1IInk4lPdLOEQMn8CjBoEQOizUS29l1ziLuYZhEnxxgPWtlrFBcVAsbIrJ8UinVw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
